Programa1: Programa1.cpp Ponto.cpp Ponto.h
	g++ Programa1.cpp Ponto.cpp -o Programa1

Programa2: Programa2.cpp Circulo.cpp Circulo.h Ponto.cpp Ponto.h
	g++ Programa2.cpp Circulo.cpp Ponto.cpp -o Programa2

